name: release-web-api

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: true
        default: "v1.0.0"
    

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build image
        run: docker build -t yaswanth1995/web-api:${{ github.ref_name }} ./app

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push image
        run: docker push yaswanth1995/web-api:${{ github.ref_name }}
        
      - name: Update image tag in kustomize
        run: |
          cd k8s/overlays/prod
          kustomize edit set image yaswanth1995/web-api=yaswanth1995/web-api:${{ github.ref_name }}
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add kustomization.yml
          git commit -m "chore: update image to ${{ github.ref_name }}"
          git push origin HEAD:main
